### PR TITLE
Add the Canal map

### PR DESCRIPTION
**Pull request by valbrimi**

### CODE REVIEW

**Comment by Restioson** [comment]
Hi, is this on build server to check out?

**Comment by valbrimi** [comment]
siege:canal

**Comment by Restioson** [comment]
I'll take a look :) Has this been tested in a dev environment to ensure all the regions are set up right, by the way?

**Comment by valbrimi** [comment]
i believe the regions work now

**Comment by Restioson** [comment]
Circling back to this now :) oops !

**Pull request merged**
