### PR TITLE
Fireworks and sound effects on gate bash, gate repair and gate bash fail.

### PR DESCRIPTION
**Pull request by diabolical17**
https://www.youtube.com/watch?v=SA5_tKXtO80

### CODE REVIEW

**Comment by Restioson** [comment]
- Gate brace sound almost sounds like it plays twice?
- I'm worried the negative bash sound would get a bit spammy
- I like the firework! Could be added to flags too eventually to help people see it
- Can you show the brace when it repairs, or is this still broken in upstream 🤔

**Comment by diabolical17** [comment]
Its still broken upstream

**Comment by diabolical17** [comment]
> Gate brace sound almost sounds like it plays twice? 

Probs because im spamming it 😅

**Comment by Restioson** [comment]
> Its still broken upstream

Okay, I will fix it and then we can see how it sounds.

>  Gate brace sound almost sounds like it plays twice?

Hmm... maybe another sound effect could be used then? Most of the time when you repair a gate or brace it you are spamming the blocks down so you don't die

**Comment by diabolical17** [comment]
> Hmm... maybe another sound effect could be used then? Most of the time when you repair a gate or brace it you are spamming the blocks down so you don't die

I could check if the user is spamming the brace. Or add a cooldown to prevent spam.

**Comment by Restioson** [comment]
> I could check if the user is spamming the brace and wait X seconds to play another effect. Or add a cooldown to prevent spam.

That works. Cooldown would change the behaviour in a way that I'm not sure that we want (making it too slow)

**Comment by Restioson** [comment]
I've fixed gate repairing upstream if you want to test how the repair sounds?

**Comment by Restioson** [comment]
Why close this?

**Pull request closed without merging**
